name: tut
channels:
  - pytorch 
  - nvidia
  - defaults
dependencies:
  - python=3.12
  - pytorch=2.2.2
  - torchvision=0.17.2
  - torchaudio=2.2.2
  - pytorch-cuda=12.1
  - numpy=1.26.4
  - jupyterlab=4.0.11
  - matplotlib=3.8.0
  - Pillow=10.2.0
  - pandas=2.2.1
  - seaborn=0.12.2
  - scikit-learn=1.3.0
  - pip
  - pip:
    - lightning==2.2.1
    - openpyxl==3.1.2
    - hydra-core==1.3.2
    - rootutils==1.0.7
