autoencoder:
  _target_: src.tutorial_lightning_15min.LitAutoEncoder
  encoder:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: torch.nn.Linear
        in_features: 784
        out_features: 64
      - _target_: torch.nn.ReLU
      - _target_: torch.nn.Linear
        in_features: 64
        out_features: 3
  decoder:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: torch.nn.Linear
        in_features: 3
        out_features: 64
      - _target_: torch.nn.ReLU
      - _target_: torch.nn.Linear
        in_features: 64
        out_features: 784

train_loader: 
  _target_: torch.utils.data.DataLoader
  dataset:
    _target_: torchvision.datasets.MNIST
    root: data
    download: true
    transform:
      _target_: torchvision.transforms.ToTensor

trainer:
  _target_: lightning.Trainer
  limit_train_batches: 100
  max_epochs: 1
