autoencoder:
  _target_: src.basic_lvl2.LitAutoEncoder
  encoder:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: torch.nn.Linear
        in_features: 784
        out_features: 64
      - _target_: torch.nn.ReLU
      - _target_: torch.nn.Linear
        in_features: 64
        out_features: 3
  decoder:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: torch.nn.Linear
        in_features: 3
        out_features: 64
      - _target_: torch.nn.ReLU
      - _target_: torch.nn.Linear
        in_features: 64
        out_features: 784

data_module:
  _target_: src.basic_lvl2.MNISTDataModule
  data_dir: data/
  batch_size: 64
  num_workers: 8

trainer:
  _target_: lightning.Trainer
  # limit_train_batches: 100
  # limit_val_batches: 100
  # limit_test_batches: 100
  max_epochs: 10
